### PR TITLE
Update east.bib

### PR DESCRIPTION
**Pull request by pchiou6932**
add Hugon's edition of Dharmottara's Pramāṇaviniścayaṭīkā chapter 3

### CODE REVIEW

**Review by paddymcall — COMMENTED** [review]
I think it would be better to have this as an ``edited volume'', something like this:

```
@Collection{,
  editor    = {Pascale Hugon},
  author =  {Dharmottara},
  date      = {2021},
  title     = {Dharmottara’s Pramāṇaviniścayaṭīkā: Chapter 3},
  subtitle = {Diplomatic Edition},
  location  = {Peking, Vienna},
  number    = {21},
  publisher = {China Tibetology Publishing House and Austrian Academy of Sciences Press},
  series    = {Sanskrit Texts from the Tibetan Autonomous Region},
}
```

It would also be good to mention the involvement of Iwata and Watanabe, but I'm not sure where.  Do you have any suggestions?

**Comment by kellner** [comment]
The entry is also incorrect insofar as the place of publication in China is Beijing, not Peking. 

Regarding the involvement of Iwata and Watanabe, it would be best if one of you could check the biblatex specification as to how such cases are handled. In this case, "Diplomatic Edition by Pascale Hugon in Collaboration with Takashi Iwata and Toshikazu Watanabe" could for example be given as the full "subtitle", but I am not expert enough in biblatex to determine whether this is the best or recommended solution.

**Review by paddymcall — COMMENTED** [review]
One option for a biblatex record would be:

```
@Collection{hugon20:_dharmottara_pvinT3,
  editor =       {Pascale Hugon},
  editora =      {Takashi Iwata and Toshikazu Watanabe},
  editortypea =  {collaborator},
  date =         2020,
  title =        {Dharmottara’s Pramāṇaviniścayaṭīkā: Chapter 3},
  subtitle =     {Diplomatic Edition},
  location =     {Beijing, Vienna},
  number =       21,
  url =          {https://epub.oeaw.ac.at/8643-4},
  doi =          {10.1553/9783700186434_STTAR021},
  publisher =    {China Tibetology Publishing House and Austrian
                  Academy of Sciences Press},
  series =       {Sanskrit Texts from the Tibetan Autonomous Region},
}
```
See section [Editorial roles](https://mirror.kumi.systems/ctan/macros/latex/contrib/biblatex/doc/biblatex.pdf#subsubsection.2.3.6) in the biblatex docs.

In EAST's bibliography style, only the main editor (Hugon) would be shown. Alternatively, one could also add the names to the standard editor field, glossing over the different roles:
```
...
  editor =       {Pascale Hugon and Takashi Iwata and Toshikazu Watanabe},
  date =         2020,
...
```


Note that according to the PDF the date is 2020, so I changed that too.

I'd also suggest adding the DOI field (and the URL field, because the DOI isn't working yet).

**Comment by kellner** [comment]
Use of "editora" would also require "editoratype", which is fine. Adding all three persons as "editor" is wrong because, well, Iwata and Watanabe are not editors (unlike Krasser and Lasic for PSṬ 1, for instance). 

I suppose there are many entries in the database where contributors or supporting editors are not shown (or not even recorded). We're not going to go through everything and check. It doesn't hurt to be precise from now on, but I also see no problem if just Hugon is shown as the editor on the website. In many library catalogues supporting roles are not recorded.

**Comment by pchiou6932** [comment]
Thanks for all the clarification and pointing out the mistake I made. 
But @paddymcall , could you clarify why you think this publication should be classified as ''collection''? According to the definition in the biblatex docs, a collection is ''with multiple, self-contained contributions by distinct
authors which have their own title. The work as a whole has no overall author but it
will usually have an editor'' 

So I think it should be classified as a book, as the UB catalog does in the case of [Pramāṇasamuccayaṭīkā](https://usearch.univie.ac.at/primo-explore/fulldisplay?docid=UWI_alma21329518810003332&context=L&vid=UWI&lang=de_DE&search_scope=UWI_UBBestand&adaptor=Local%20Search%20Engine&isFrbr=true&tab=default_tab&query=any,contains,Jinendrabuddhi%E2%80%99s%20Vi%C5%9B%C4%81l%C4%81malavat%C4%AB%20Pram%C4%81%E1%B9%87asamuccaya%E1%B9%AD%C4%ABk%C4%81%20Chapter%202&sortby=date&facet=frbrgroupid,include,628040490&offset=0)

**Comment by paddymcall** [comment]
> Thanks for all the clarification and pointing out the mistake I made.
> But @paddymcall , could you clarify why you think this publication should be classified as ''collection''? According to the definition in the biblatex docs, a collection is ''with multiple, self-contained contributions by distinct
> authors which have their own title. The work as a whole has no overall author but it
> will usually have an editor''

I said that mainly out of my own biblatex habits, which are at least in part only practical.  But I do also think that the roles that Pascale Hugon and Dharmottara have in this publication are closer to that of editor and author in an edited volume rather than to that of author and work in a book.  It is true that there are not multiple contributions here, but the criteria of "self-contained" and "distinct authors" seem to hold true. 

Plus, if we treat this as a "book" rather than as a "collection", we'll get into difficulties with books containing more than one work.  This would be the issue for any bibliographic item containing base-text, commentary, and/or classical translations. 

If you want to go with book in this case, perhaps this would be best:

```
@Book{hugon20:_dharmottara_pvinT3,
  editor =       {Pascale Hugon},
  editora =      {Takashi Iwata and Toshikazu Watanabe},
  editoratype =  {collaborator},
  date =         2020,
  author =       {Dharmottara},
  title =        {Dharmottara’s Pramāṇaviniścayaṭīkā: Chapter 3},
  subtitle =     {Diplomatic Edition},
  location =     {Beijing, Vienna},
  number =       21,
  url =          {https://epub.oeaw.ac.at/8643-4},
  doi =          {10.1553/9783700186434_STTAR021},
  publisher =    {China Tibetology Publishing House and Austrian
                  Academy of Sciences Press},
  series =       {Sanskrit Texts from the Tibetan Autonomous Region},
}
```


> 
> So I think it should be classified as a book, as the UB catalog does in the case of [Pramāṇasamuccayaṭīkā](https://usearch.univie.ac.at/primo-explore/fulldisplay?docid=UWI_alma21329518810003332&context=L&vid=UWI&lang=de_DE&search_scope=UWI_UBBestand&adaptor=Local%20Search%20Engine&isFrbr=true&tab=default_tab&query=any,contains,Jinendrabuddhi%E2%80%99s%20Vi%C5%9B%C4%81l%C4%81malavat%C4%AB%20Pram%C4%81%E1%B9%87asamuccaya%E1%B9%AD%C4%ABk%C4%81%20Chapter%202&sortby=date&facet=frbrgroupid,include,628040490&offset=0)

They also declare edited volumes as book entries, so I think this is not a good reason.  In general, the automatically generated items from library catalogues are not ideal.  They are optimised for search and connectivity (linking persons, e.g.), and not necessarily what we are aiming for in EAST.  Example: https://ubdata.univie.ac.at/AC06461323 , exports as a book.  Biblatex comes with a good set of examples in: https://mirror.kumi.systems/ctan/macros/latex/contrib/biblatex/doc/examples/biblatex-examples.bib . A relevant one is this:

```
@book{aristotle:anima,
  author       = {Aristotle},
  title        = {De Anima},
  date         = 1907,
  editor       = {Hicks, Robert Drew},
  publisher    = cup,
  location     = {Cambridge},
  keywords     = {primary},
  langid       = {english},
  langidopts   = {variant=british},
  annotation   = {A \texttt{book} entry with an \texttt{author} and an
                  \texttt{editor}},
}
```

But as I said, this might not work so well for publications with combined texts (of which we have many).

I attach an example of the formatted results, with pretty default biblatex settings.  You'll see that the collection-type entry is also closer to what we'd customarily expect in a bibliography (this is where my "practical habits" come from):

```
%% simulate bib file:
\begin{filecontents}{\jobname.bib}
@Book{hugon20,
  editor =       {Pascale Hugon},
  editora =      {Takashi Iwata and Toshikazu Watanabe},
  editoratype =  {collaborator},
  date =         2020,
  author =       {Dharmottara},
  title =        {Dharmottara’s Pramāṇaviniścayaṭīkā: Chapter 3},
  subtitle =     {Diplomatic Edition},
  location =     {Beijing, Vienna},
  number =       21,
  url =          {https://epub.oeaw.ac.at/8643-4},
  doi =          {10.1553/9783700186434_STTAR021},
  publisher =    {China Tibetology Publishing House and Austrian
                  Academy of Sciences Press},
  series =       {Sanskrit Texts from the Tibetan Autonomous Region},
}
@Collection{hugon20_coll,
  editor =       {Pascale Hugon},
  editora =      {Takashi Iwata and Toshikazu Watanabe},
  editoratype =  {collaborator},
  date =         2020,
  author =       {Dharmottara},
  title =        {Dharmottara’s Pramāṇaviniścayaṭīkā: Chapter 3},
  subtitle =     {Diplomatic Edition},
  location =     {Beijing, Vienna},
  number =       21,
  url =          {https://epub.oeaw.ac.at/8643-4},
  doi =          {10.1553/9783700186434_STTAR021},
  publisher =    {China Tibetology Publishing House and Austrian
                  Academy of Sciences Press},
  series =       {Sanskrit Texts from the Tibetan Autonomous Region},
}
\end{filecontents}
% % document:
\documentclass{article}

\usepackage[%
backend=biber,
citestyle=authoryear,
bibstyle=authortitle,
sortlocale=en,
]{biblatex}



\addbibresource{\jobname.bib}


\begin{document}
\begin{itemize}
\item Variant 1 (book type): \fullcite{hugon20}
\item Variant 2 (collection type): \fullcite{hugon20_coll}
\end{itemize}

% \printbibliography
\end{document}
```
[tests.pdf](https://github.com/ea-east/east-biblio/files/5809125/tests.pdf)

**Comment by kellner** [comment]
simple question: surely this is not the first critical edition we have in EAST. Have these so far been classified as books or as collections?

**Comment by pchiou6932** [comment]
I see inconsistency in EAST in this regard. We do have some publications containing more than one text classified as collection, but we have more such publications and publication containing a single text (or a single text plus an annotated translation, etc.) classified as a book.

**Comment by paddymcall** [comment]
In the live database, they have usually been classified as book type entries, but this is mainly due to the fact that they have been automatically created from Tamboti's MODS records which record the genre as "book".  But not unlike the issue with the library export, this is perhaps not ideal.  I think it's fine to have either book (if there's only one author for the edited text) or collection (if there's more than one author), but the editors (even if they are editors of diplomatic or critical editions) should in my opinion not be recorded as authors of the book.  Depending on the decision we reach on this issue, we should then clean up the bibliography.

**Comment by kellner** [comment]
It seems plausible to me to record the (diplomatic or critical) editor as editor and make the publication type dependent on singular author (book) or several authors (collection), but this would then also imply that editions need an author, which is the author of the edited text (or several authors, if it's e.g. a base text with a commentary, author could also be "anonymous").

Since all publications which are editions are marked as such in our database, it should not be too difficult to do a cleanup. 

Question is whether this doesn't also have implications for editions of canonical translations (Tibetan, mostly, and Chinese).

**Comment by kellner** [comment]
I believe now that we have to rethink the issue entirely. A book that contains an edition involves the person who is responsible for it (may also be several) in different roles: as author of preface or introduction, or of a bibliography, as well as as editor of the edited text. 

If we classify an edition as a book with an author, this is correct for intro, etc., but strictly speaking not correct as far as the edited text is concerned. 

If we classify an edition as a collection with different parts and mark the reponsible person as editor, this is correct for the edited text, but not for preface, intro, etc. In this case, moreover, the page-numbers of the edited text would have to be supplied for all editions contained in the database (which we don't have know, a lot of extra work!). 

We can solve this in different ways. 

1) Mark the edition as a book, and add text-specific information ("this is a critical edition of a work by such-and-such") through the database. This is what we do now. 

2) Mark the edition as a collection (or rather: incollection), and do a lot of cleanup. 

I would prefer 1) and hence revise my previous position. This results in slight inaccuracies from a bibliographical perspective, but the consequences in terms of workload of 2) are too large (and the gain in accuracy does not justify the workload). 

We should reach a decision on the matter in the next meeting. Can someone please summarize the issue and prepare the pros and cons for discussion at the May meeting?

**Comment by pchiou6932** [comment]
I can summarizes and raise the issue in our next meeting.

btw, I found whether a @Collection entry or a @book entry is created in the Django, as long as there is the author field, the entry is shown in Bibtext as @book, see: https://east.ikga.oeaw.ac.at/bib/28553/.

**Review by paddymcall — APPROVED** [review]
Thanks, this looks good!

The only additional complaint by biber (vs. the master branch) is that we have a collection item with an author, item east:28553.  This seems to be disallowed by biblatex's datamodel.  Since we'll have to discuss this in more detail anyway, let's ignore this for now.

**Pull request merged**
